#!/usr/bin/env python3
"""Single supported generator for PLANO:CQ /1/<id>/ links. Python 3 + gh."""
import argparse
import base64
from html import escape
from html.parser import HTMLParser
import json
import os
import re
import subprocess
import sys
import time
from urllib.request import urlopen

REPO = 'planocq/planocq.github.io'
BASE = 'https://planocq.github.io'
KEYS = ('description', 'og:title', 'og:description', 'og:type', 'og:image',
        'og:image:width', 'og:image:height', 'og:image:alt', 'twitter:card',
        'twitter:title', 'twitter:description', 'twitter:image')


class Metadata(HTMLParser):
    def __init__(self, text):
        super().__init__()
        self.values = {}
        self.feed(text)

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == 'meta':
            key = a.get('property', a.get('name'))
            if key:
                self.values[key] = a.get('content', '')
        if tag == 'link' and a.get('rel') == 'canonical':
            self.values['canonical'] = a.get('href')


def valid_id(value):
    if not re.fullmatch(r'[1-9][0-9]*', str(value)):
        raise ValueError('ID debe ser un entero positivo sin ceros iniciales')
    return str(value)


def render(home, link_id):
    url = f'{BASE}/1/{valid_id(link_id)}/'
    values = Metadata(home).values
    for key in KEYS:
        if not values.get(key):
            raise ValueError(f'Metadata de home incompleta: {key}')
    for key in ('og:image', 'twitter:image'):
        if not values[key].startswith('https://'):
            raise ValueError(f'{key} debe ser HTTPS absoluta')
    tags = []
    for key in KEYS:
        attr = 'property' if key.startswith('og:') else 'name'
        tags.append(f'    <meta {attr}="{key}" content="{escape(values[key], quote=True)}" />')
    head = '\n'.join(tags)
    return f'''<!doctype html>
<!-- Generated by tools/unique_link.py; do not edit manually. -->
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="robots" content="noindex, nofollow" />
    <title>{escape(values['og:title'])}</title>
{head}
    <meta property="og:url" content="{url}" />
    <link rel="canonical" href="{url}" />
    <style>html, body {{ margin: 0; min-height: 100%; background: #101010; }}</style>
  </head>
  <body>
    <script>
      fetch("/")
        .then((response) => {{
          if (!response.ok) throw new Error("No se pudo cargar el sitio");
          return response.text();
        }})
        .then((html) => {{
          // Keep this link's identity after loading the normal home and beacon.
          const page = new DOMParser().parseFromString(html, "text/html");
          page.head.querySelectorAll('link[rel="canonical"], meta[property="og:url"]').forEach(el => el.remove());
          const canonical = page.createElement("link");
          canonical.rel = "canonical";
          canonical.href = "{url}";
          page.head.appendChild(canonical);
          const identity = page.createElement("meta");
          identity.setAttribute("property", "og:url");
          identity.content = "{url}";
          page.head.appendChild(identity);
          document.open();
          document.write("<!doctype html>" + page.documentElement.outerHTML);
          document.close();
        }});
    </script>
  </body>
</html>
'''


def api(path, data=None):
    env = os.environ.copy()
    if not env.get('GH_TOKEN') and not env.get('GITHUB_TOKEN'):
        env['GH_TOKEN'] = subprocess.check_output(
            ['gh', 'auth', 'token', '--user', 'planocq'], text=True).strip()
    cmd = ['gh', 'api', f'repos/{REPO}/{path}']
    if data is not None:
        cmd += ['--method', 'POST', '--input', '-']
    return json.loads(subprocess.check_output(cmd, env=env, text=True,
                      input=json.dumps(data) if data is not None else None))


def create(requested='auto', test=False):
    # A commit based on this head + non-forced ref update prevents concurrent
    # creators from overwriting one another. On conflict rerun; no URL was assigned.
    head = api('git/ref/heads/main')['object']['sha']
    tree_sha = api('git/commits/' + head)['tree']['sha']
    tree = api('git/trees/' + tree_sha + '?recursive=1')
    if tree.get('truncated'):
        raise ValueError('Árbol truncado: no es seguro asignar ID')
    used = {int(m.group(1)) for item in tree['tree']
            if (m := re.match(r'^1/([0-9]+)(?:/|$)', item['path']))}
    link_id = str(max(used, default=0) + 1) if requested == 'auto' else valid_id(requested)
    if int(link_id) in used:
        raise ValueError(f'ID {link_id} ya existe; no se sobrescribe ni reutiliza')
    home_file = api('contents/index.html?ref=' + head)
    home = base64.b64decode(home_file['content']).decode()
    page = render(home, link_id)
    newtree = api('git/trees', {'base_tree': tree_sha, 'tree': [
        {'path': f'1/{link_id}/index.html', 'mode': '100644', 'type': 'blob', 'content': page}
    ]})['sha']
    kind = 'TEST RESERVED' if test else 'commercial'
    commit = api('git/commits', {'message': f'Create {kind} link /1/{link_id}/ via unique_link.py',
                                'tree': newtree, 'parents': [head]})['sha']
    api('git/refs/heads/main', {'sha': commit, 'force': False})
    result = {'id': link_id, 'url': f'{BASE}/1/{link_id}/', 'commit': commit,
              'status': 'PUBLICADO_EN_REPO', 'test_reserved': test}
    # Print immediately: if deployment verification times out, use verify on this
    # ID rather than create again. Never output a successful allocation before push.
    print(json.dumps(result), flush=True)
    return link_id


def fetch(url):
    with urlopen(url, timeout=20) as r:
        if r.status != 200 or r.url != url:
            raise ValueError(f'Status o redirect inesperado: {r.status} {r.url}')
        return r.headers.get_content_type(), r.read()


def verify(link_id, wait=0):
    url = f'{BASE}/1/{valid_id(link_id)}/'
    deadline = time.monotonic() + wait
    while True:
        try:
            content_type, raw = fetch(url)
            if content_type != 'text/html':
                raise ValueError('La página no devuelve text/html')
            page = raw.decode()
            values = Metadata(page).values
            home_type, home_raw = fetch(BASE + '/')
            expected = Metadata(home_raw.decode()).values
            for key in KEYS:
                if not values.get(key) or values[key] != expected.get(key):
                    raise ValueError(f'Metadata no coincide con home: {key}')
            if values.get('og:url') != url or values.get('canonical') != url:
                raise ValueError('La identidad de la URL no coincide')
            if values.get('robots') != 'noindex, nofollow':
                raise ValueError('Falta noindex')
            if 'fetch("/")' not in page or 'static.cloudflareinsights.com/beacon.min.js' not in home_raw.decode():
                raise ValueError('Falta cargador o beacon de tracking')
            if not values['og:image'].startswith('https://'):
                raise ValueError('Imagen no absoluta HTTPS')
            image_type, _ = fetch(values['og:image'])
            if not image_type.startswith('image/'):
                raise ValueError('Imagen no accesible como imagen')
            print(json.dumps({'id': str(link_id), 'url': url, 'status': 'VERIFICADO',
                              'http': 200, 'metadata_without_js': True, 'image': values['og:image']}))
            return
        except Exception:
            if time.monotonic() >= deadline:
                raise
            time.sleep(5)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest='command', required=True)
    new = commands.add_parser('create', help='Assign ID, generate, publish and verify one new link')
    new.add_argument('--id', default='auto', help='auto (default) or unused positive integer')
    new.add_argument('--test', action='store_true', help='Reserve this link for testing, not a recipient')
    new.add_argument('--wait', type=int, default=180, help='Seconds to wait for Pages')
    check = commands.add_parser('verify', help='Read-only verification; never creates a link')
    check.add_argument('id')
    check.add_argument('--wait', type=int, default=0)
    args = parser.parse_args()
    if args.command == 'create':
        link_id = create(args.id, args.test)
        verify(link_id, args.wait)
    else:
        verify(args.id, args.wait)


if __name__ == '__main__':
    try:
        main()
    except Exception as exc:
        print(f'ERROR: {exc}. Si ya se imprimió un ID, usar verify ID; no repetir create.', file=sys.stderr)
        sys.exit(1)
